FROM continuumio/miniconda3

WORKDIR /usr/src/app

#Create the environment
COPY ./fragment-based-dgm/environment.yml environment.yml
RUN conda env create -f environment.yml

COPY ./fragment-based-dgm ./p

SHELL ["conda", "run", "-n", "aistats2020", "/bin/","bash", "-c"]

# RUN echo "Image is running"

WORKDIR ./p

EXPOSE 8080

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "aistats2020", "python", "manager.py"]

